--- #YAML:1.0
name:               Text-Format-Screenplay
version:            0.01
abstract:           Create a movie screenplay PDF from text.
author:
    - Tom Kirchner <tk@local>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    File::Slurp:  0
    PDF::Create:  0
    Text::Wrap:   0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
